Developed an improved notification system FINANCEHELPER-28
officer04/finance-helper pull request #5
Opened 2024-10-19 00:21 UTC by officer04

2024-10-19 02:21 UTC, egor4yt requested changes

2024-10-19 02:21 UTC, egor4yt commented on src/components/App.tsx
> +import { useAppSelector } from '../redux/hooks';
useAppSelector, SnackbarAll, useState - мусор

2024-10-19 02:21 UTC, egor4yt commented on src/components/shared/form-authorization.tsx
>        })
Бесполезный кусок кода. Если catch не обрабатывается - так и не пиши

2024-10-19 02:21 UTC, egor4yt commented on src/components/shared/form-register.tsx
>        })
код не используется

2024-10-19 02:21 UTC, egor4yt commented on src/components/shared/form-update-user.tsx
> +        );
А как же использовать библиотеку для локализации?

2024-10-19 02:21 UTC, egor4yt commented on src/components/shared/home.tsx
> +      </Snackbar> */}
Не используемый код

2024-10-19 02:21 UTC, egor4yt commented on src/middlewares/notification-middleware.ts
> +              }),
1. константы типа 'ru' не используй, у тебя для них файл есть специальный
2. заменить условие на if language === английский, else if if language === русский, else throw new Error("Unsupported language")

2024-10-19 02:21 UTC, egor4yt commented on src/types/ui/snackbar/snackbar-info-notification-type.ts
> +}
Не сложное имя? Может просто NotificationType?

2024-10-19 02:23 UTC, egor4yt commented on src/components/shared/home.tsx
>    const [openSnackbar, setOpenSnackbar] = useState(false);
openSnackbar - мусор

2024-10-19 02:23 UTC, egor4yt commented on src/components/shared/home.tsx
>  import { useAppSelector } from '../../redux/hooks';
Snackbar, Alert - мусор

2024-10-19 02:27 UTC, officer04 commented on src/components/shared/form-register.tsx
>        })
+

2024-10-21 16:16 UTC, egor4yt requested changes
Некоторые ошибки не были исправлены

2024-10-21 16:16 UTC, egor4yt commented on src/components/shared/home.tsx
>    const [openSnackbar, setOpenSnackbar] = useState(false);
openSnackbar - мусо

2024-10-21 16:16 UTC, egor4yt commented on src/components/shared/home.tsx
>          </div>
handleCloseSnackbar - не используется
notification - не используется

2024-10-21 16:16 UTC, egor4yt commented on src.zip
Лишний файл

2024-10-21 16:16 UTC, egor4yt commented on src/middlewares/notification-middleware.ts
> +        store.dispatch(
условие payload.detail дублируется два раза - вынеси в общий if снаружи

2024-10-21 16:16 UTC, egor4yt commented on src/middlewares/notification-middleware.ts
> +        store.dispatch(
if (payload.statusCode === 409 || payload.statusCode === 403) - можно объединить в один if

2024-10-21 16:16 UTC, egor4yt commented on src/middlewares/notification-middleware.ts
> +          language === ApplicationLanguage.RUSSIAN
else {
 if (language == ru) {}
 else if (language == en) {}
 else throw new Error("Unsupported language");
}

2024-10-21 16:16 UTC, egor4yt commented on src/middlewares/notification-middleware.ts
> +          language === ApplicationLanguage.RUSSIAN
А лучше вообще switch (language) {
 'ru': ...
 'en' ...
 default: throw new Error('Unsupported language')
}

2024-10-22 17:35 UTC, officer04 commented on src.zip
+

2024-10-22 18:02 UTC, egor4yt approved these changes

2024-10-22 18:03 UTC, merged